// Code generated by protoc-gen-go. DO NOT EDIT.
// source: whoami.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	whoami.proto

It has these top-level messages:
	Request
	Response
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Response struct {
	ServerName    string `protobuf:"bytes,1,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	ClientIp      string `protobuf:"bytes,2,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	ClientIssuer  string `protobuf:"bytes,3,opt,name=client_issuer,json=clientIssuer" json:"client_issuer,omitempty"`
	ClientSubject string `protobuf:"bytes,4,opt,name=client_subject,json=clientSubject" json:"client_subject,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func (m *Response) GetClientIp() string {
	if m != nil {
		return m.ClientIp
	}
	return ""
}

func (m *Response) GetClientIssuer() string {
	if m != nil {
		return m.ClientIssuer
	}
	return ""
}

func (m *Response) GetClientSubject() string {
	if m != nil {
		return m.ClientSubject
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Whoami service

type WhoamiClient interface {
	Whoami(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type whoamiClient struct {
	cc *grpc.ClientConn
}

func NewWhoamiClient(cc *grpc.ClientConn) WhoamiClient {
	return &whoamiClient{cc}
}

func (c *whoamiClient) Whoami(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.Whoami/Whoami", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Whoami service

type WhoamiServer interface {
	Whoami(context.Context, *Request) (*Response, error)
}

func RegisterWhoamiServer(s *grpc.Server, srv WhoamiServer) {
	s.RegisterService(&_Whoami_serviceDesc, srv)
}

func _Whoami_Whoami_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WhoamiServer).Whoami(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Whoami/Whoami",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WhoamiServer).Whoami(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Whoami_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Whoami",
	HandlerType: (*WhoamiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Whoami",
			Handler:    _Whoami_Whoami_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whoami.proto",
}

func init() { proto.RegisterFile("whoami.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x31, 0xcf, 0x82, 0x30,
	0x10, 0x86, 0x3f, 0xf8, 0x0c, 0xc2, 0x81, 0x0e, 0x9d, 0x1a, 0x1d, 0x34, 0x18, 0x12, 0x27, 0x4c,
	0xf4, 0x57, 0xb8, 0x38, 0xe0, 0xe0, 0x48, 0x28, 0xb9, 0x44, 0x8c, 0xd0, 0xda, 0x2b, 0xfa, 0x47,
	0xfc, 0xc1, 0x26, 0x6d, 0x75, 0xbb, 0x7b, 0xde, 0xe7, 0x92, 0xf7, 0x20, 0x7b, 0x5d, 0x65, 0xd3,
	0x77, 0xa5, 0xd2, 0xd2, 0x48, 0x16, 0x2a, 0x91, 0x27, 0x30, 0xad, 0xf0, 0x31, 0x22, 0x99, 0xfc,
	0x1d, 0x40, 0x5c, 0x21, 0x29, 0x39, 0x10, 0xb2, 0x15, 0xa4, 0x84, 0xfa, 0x89, 0xba, 0x1e, 0x9a,
	0x1e, 0x79, 0xb0, 0x0e, 0xb6, 0x49, 0x05, 0x0e, 0x9d, 0x9a, 0x1e, 0xd9, 0x12, 0x92, 0xf6, 0xde,
	0xe1, 0x60, 0xea, 0x4e, 0xf1, 0xd0, 0xc6, 0xb1, 0x03, 0x47, 0xc5, 0x36, 0x30, 0xfb, 0x86, 0x44,
	0x23, 0x6a, 0xfe, 0x6f, 0x85, 0xcc, 0x0b, 0x96, 0xb1, 0x02, 0xe6, 0x5e, 0xa2, 0x51, 0xdc, 0xb0,
	0x35, 0x7c, 0x62, 0x2d, 0x7f, 0x7a, 0x76, 0x70, 0xbf, 0x83, 0xe8, 0x62, 0x5b, 0xb3, 0xe2, 0x37,
	0xa5, 0xa5, 0x12, 0xa5, 0xef, 0xbd, 0xc8, 0xdc, 0xe2, 0x8a, 0xe7, 0x7f, 0x22, 0xb2, 0xdf, 0x1d,
	0x3e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x04, 0xd8, 0x6f, 0xed, 0x00, 0x00, 0x00,
}
